---
sidebar: false
toc: false
---

# Introduction to RShiny

| Audience | Computational skills required| Duration |
:----------|:----------|:----------|
| Biologists | [Introduction to R](https://hbctraining.github.io/Intro-to-R-flipped/) | 2-session online workshop (4 hours of trainer-led time)|

# Description

This repository has teaching materials for a 2 hands-on workshops lasting **2 hours** each covering RShiny. RShiny is an R package that allows users to create interactive web applications for their data. In this hands-on workshop, we will introduce the basic syntax and structure for RShiny applications, create a variety of applications using a diverse set of inputs and discuss options for hosting these applications.

*This workshop assumes that users have a basic grasp of coding within R.*

# Learning Objectives

In this workshop, users will be able to:

- Differentiate between the User Interface and Server side of a RShiny App
- Create apps that take a variety of input formats, including text, checkboxes, dropdown menus and sliders
- Visualize text, figure and table output using an RShiny App
- Upload data into an RShiny app and download data and figures from an RShiny app
- Discuss the various hosting options for RShiny Apps 
- Modify R Shiny apps by editing a CSS file

### Lessons

::: callout-note
These materials were developed for a trainer-led workshop, but are also amenable to self-guided learning.
:::

* [Workshop schedule (trainer-led learning)](schedule/schedule_AZ.qmd)
* [Self-learning](schedule/self-learning.qmd)


## Installation Requirements

Download the most recent versions of R and RStudio for your laptop:

 - [R](http://lib.stat.cmu.edu/R/CRAN/) **(version 4.3.0 or above)**
 - [RStudio](https://www.rstudio.com/products/rstudio/download/#download)

:::callout-note
**If you have a Mac,** download and install [this tool](https://mac.r-project.org/tools/gfortran-12.2-universal.pkg) before installing your packages if using R versions 4.3.0 up to 4.4.3 or [this tool](https://mac.r-project.org/tools/gfortran-14.2-universal.pkg) if using R versions after 4.4.3.
:::

## R Package requirements:

Install the 4 packages listed below from **CRAN** using the `install.packages()` function. 
```{r}
#| label: install_packages
#| eval: false
install.packages("shiny")
install.packages("tidyverse")
install.packages("shinythemes")
install.packages("DT")
```

## Additional Resources

- [Mastering Shiny](https://mastering-shiny.org/)

---
