---
title: "Hosting Options for RShiny Apps"
description: |
  This lesson introduces participants to various options for hosting RShiny applications. Participants will compare local usage, traditional server hosting including Posit Connect. Practical considerations, eligibility, advantages and limitations of each hosting method are discussed to encourage developers to select the best solution for their RShiny app deployment needs.
author:
  - Will Gammerdinger
  - Meeta Mistry
date: "2025-11-11"
categories: 
  - R
  - Shiny
  - App Deployment
  - Server Hosting
  - Web Applications
keywords:
  - R Shiny
  - Shiny Hosting
  - App Deployment
  - Serverless
  - Shinylive
  - Posit Connect
  - Shinyapps.io

license: "CC-BY-4.0"
editor_options: 
  markdown: 
    wrap: 72
---

# Learning Objectives

In this lesson, you will:

- Describe Shiny app hosting options

# App Hosting

When one develops an app, they are commonly placed on a server that makes the app accessible to a broader audience. These servers are connected to the internet and thus allow users to utilize your app globally, any time of day. However, there are computational needs to hosting these apps and costs associated with running the servers behind these apps. We will briefly discuss a few options that app developers have for distributing their apps. 

## Local usage

One option for distributing your app is for it to be run on people's own computers (locally). If your app is small-scale, this might be a reasonable solution in order to escape the fees associated with running a server to host your app, since this can be done for free. However, one issue with this approach is that it is sensitive to version issues. If a developer develops their app with a certain version of a given package and the user is using a different version, there could be version incapabilities. For this reason alone, sharing apps to be run locally is not considered a great practice.

## Server Hosting

As we previously mentioned, the most common way for apps to hosted is via servers. One nice aspect of hosting an app within a server is that the version concerns of running an app locally disappears because the developer's versions of the loaded packages are the ones that are used on the server. One way that you might choose to host your apps on a server using Posit Connect.

### Posit Connect

One option for hosting your Shiny apps is to use [Posit Connect](https://posit.co/products/enterprise/connect/). Uploading apps through this platform has a few advantages:

1. Uploading apps is simple
2. It allows you to control access to who can see and use your app. You can let anyone use it, require a login or only invite certain people to be able to use it
3. You can give it a custom URL

***

[Next Lesson >>](08_layout_practical.qmd)

[Back to Schedule](..)

*** 

*This lesson has been developed by members of the teaching team at the [Harvard Chan Bioinformatics Core (HBC)](http://bioinformatics.sph.harvard.edu/). These are open access materials distributed under the terms of the [Creative Commons Attribution license](https://creativecommons.org/licenses/by/4.0/) (CC BY 4.0), which permits unrestricted use, distribution, and reproduction in any medium, provided the original author and source are credited.*