---
sidebar: false
toc: false
---

# Introduction to RShiny

## Workshop Schedule

### Day 1

| Time |  Topic  | Instructor |
|:-----------:|:----------:|:--------:|
| 9:00 - 9:15 | [Workshop introduction](../slides/workshop_intro_slides.pdf) |  Will |
| 9:15 - 9:35 | [R Shiny App Structure and Syntax](01_syntax_and_structure.qmd) | Will |
| 9:35 - 10:35 | [Input options](02_inputs.qmd) | Will |
| 10:35 - 10:40 | Break | |
| 10:40 - 11:10 | [Visualization and Interactive Visuals](03_visuals.qmd) |  Will |
| 11:10 - 11:30 | [Uploading and Downloading Data](04_uploading_downloading_data.qmd) |  Will |


### Day 2

| Time |  Topic  | Instructor |
|:-----------:|:----------:|:--------:|
| 9:00 - 9:45 | [Layouts](05_layouts.qmd) | Will |
| 9:45 - 10:30 | [Customization](06_CSS.qmd) |
| 10:30 - 10:35 | Break | |
| 10:35 - 10:50 | [Hosting Platforms](07_hosting.qmd) | Will |
| 10:50 - 11:20 | [Practical](08_practical.qmd) | Will |
| 11:20 - 11:30 | [Workshop Wrap-up](../slides/Workshop_wrapup.pdf) | Will |

# Additional Resources

[Advanced Inputs](advanced_inputs.qmd)
[Shiny Live](shinylive.qmd)

---

*These materials have been developed by members of the teaching team at the [Harvard Chan Bioinformatics Core (HBC)](http://bioinformatics.sph.harvard.edu/). These are open access materials distributed under the terms of the [Creative Commons Attribution license](https://creativecommons.org/licenses/by/4.0/) (CC BY 4.0), which permits unrestricted use, distribution, and reproduction in any medium, provided the original author and source are credited.*