---
sidebar: false
toc: false
---

# Introduction to RShiny

## Workshop Schedule

### Day 1

| Time |  Topic  | Instructor |
|:-----------:|:----------:|:--------:|
| 9:00 - 9:15 | [Workshop introduction](../slides/workshop_intro_slides.pdf) |  Will |
| 9:15 - 9:35 | [R Shiny App Structure and Syntax](../lessons/01_syntax_and_structure.qmd) | Will |
| 9:35 - 10:10 | [Input options](../lessons/02_inputs.qmd) | Will |
| 10:10 - 10:15 | Break | |
| 10:15 - 10:45 | [Visualization and Interactive Visuals](../lessons/03_visuals.qmd) |  Will |
| 10:45 - 11:00 | [Practical](../lessons/04_input_practical.qmd) | Will |


### Day 2

| Time |  Topic  | Instructor |
|:-----------:|:----------:|:--------:|
| 09:00 - 9:20 | [Uploading and Downloading Data](../lessons/05_uploading_downloading_data.qmd) |  Will |
| 9:20 - 10:00 | [Layouts](../lessons/06_layouts.qmd) | Will |
| 10:00 - 10:05 | Break | |
| 10:05 - 10:25 | [Hosting Platforms](../lessons/07_hosting.qmd) | Will |
| 10:25 - 10:50 | [Practical](../lessons/08_layout_practical.qmd) | Will |
| 10:50 - 11:00 | [Workshop Wrap-up](../slides/Workshop_wrapup.pdf) | Will |

# Additional Resources

- [Customization](../lessons/Aside_CSS.qmd)
- [Advanced Inputs](../lessons/Aside_advanced_inputs.qmd)
- [Shiny Live](../lessons/Aside_shinylive.qmd)
- [Mastering Shiny](https://mastering-shiny.org/)

## Interesting Input Widgets

- [Picker](https://github.com/hms-dbmi/picker)
- [shinyChakraSlider](https://github.com/stla/shinyChakraSlider)

---

*These materials have been developed by members of the teaching team at the [Harvard Chan Bioinformatics Core (HBC)](http://bioinformatics.sph.harvard.edu/). These are open access materials distributed under the terms of the [Creative Commons Attribution license](https://creativecommons.org/licenses/by/4.0/) (CC BY 4.0), which permits unrestricted use, distribution, and reproduction in any medium, provided the original author and source are credited.*